In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,5)

In [3]:
arr

array([[ 0.5170429 ,  0.14541425,  0.64367156,  0.04314581,  0.33588955],
       [ 0.1806138 ,  0.09485069,  0.72618948,  0.52303466,  0.48419311],
       [ 0.76030569,  0.72790898,  0.44272214,  0.5967931 ,  0.07343348]])

In [4]:
# sort函数不返回任何值, 作用在原数据上

arr.sort()

In [5]:
arr

array([[ 0.04314581,  0.14541425,  0.33588955,  0.5170429 ,  0.64367156],
       [ 0.09485069,  0.1806138 ,  0.48419311,  0.52303466,  0.72618948],
       [ 0.07343348,  0.44272214,  0.5967931 ,  0.72790898,  0.76030569]])

In [6]:
# 上面的数据已经改变, 重新创建一组数据

arr_2 = np.random.rand(3,5)

In [7]:
arr_2

array([[ 0.3858769 ,  0.21936524,  0.21973616,  0.03880085,  0.53571959],
       [ 0.66030207,  0.28957006,  0.69184168,  0.94794062,  0.58476991],
       [ 0.81227393,  0.54695971,  0.21986702,  0.72433933,  0.96935868]])

In [8]:
# 不加axis参数的话, 默认是1

arr_2.sort(axis=0)

In [9]:
arr_2

array([[ 0.3858769 ,  0.21936524,  0.21973616,  0.03880085,  0.53571959],
       [ 0.66030207,  0.28957006,  0.21986702,  0.72433933,  0.58476991],
       [ 0.81227393,  0.54695971,  0.69184168,  0.94794062,  0.96935868]])

In [10]:
arr_3 = np.random.rand(3,5)

In [11]:
arr_3

array([[ 0.89115691,  0.34694083,  0.52238606,  0.16874284,  0.7170538 ],
       [ 0.97633336,  0.88330898,  0.56071517,  0.24576435,  0.59428692],
       [ 0.36107726,  0.64286971,  0.93871302,  0.93456772,  0.61383299]])

In [12]:
# np.sort排序返回的是数组的排序副本, 原数组为改变

np.sort(arr_3)

array([[ 0.16874284,  0.34694083,  0.52238606,  0.7170538 ,  0.89115691],
       [ 0.24576435,  0.56071517,  0.59428692,  0.88330898,  0.97633336],
       [ 0.36107726,  0.61383299,  0.64286971,  0.93456772,  0.93871302]])

In [13]:
arr_3

array([[ 0.89115691,  0.34694083,  0.52238606,  0.16874284,  0.7170538 ],
       [ 0.97633336,  0.88330898,  0.56071517,  0.24576435,  0.59428692],
       [ 0.36107726,  0.64286971,  0.93871302,  0.93456772,  0.61383299]])

In [14]:
# 也可以加上axis参数

np.sort(arr_3, axis=0)

array([[ 0.36107726,  0.34694083,  0.52238606,  0.16874284,  0.59428692],
       [ 0.89115691,  0.64286971,  0.56071517,  0.24576435,  0.61383299],
       [ 0.97633336,  0.88330898,  0.93871302,  0.93456772,  0.7170538 ]])