In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5, 4)

In [3]:
arr

array([[-0.20819861,  1.4125851 ,  0.36112065, -0.06394789],
       [-0.22453547,  1.12573617, -0.15984667, -0.88381354],
       [ 1.45089882, -0.8278505 , -2.41829179,  0.14818311],
       [-1.39316694,  0.75286462,  0.86777929,  1.02745782],
       [-0.79822591,  0.13013213, -0.67339302,  1.09026675]])

In [4]:
# 数组求和
arr.sum()

0.71575410807431816

In [5]:
# 数组求均值
arr.mean()

0.035787705403715911

In [6]:
arr.sum(axis=0)

array([-1.17322811,  2.59346752, -2.02263154,  1.31814624])

In [7]:
arr.sum(axis=1)

array([ 1.50155925, -0.14245951, -1.64706037,  1.25493479, -0.25122005])

In [8]:
arr.min()

-2.4182917941852438

In [9]:
arr.max()

1.4508988153000646

In [10]:
arr.max(axis=0)

array([ 1.45089882,  1.4125851 ,  0.86777929,  1.09026675])

In [12]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#  累加和
arr_2.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [16]:
arr_2.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [17]:
arr_2.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [18]:
arr_2.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [19]:
# 大于0的个数
(arr > 0).sum()

10

In [20]:

arr.all()

True