In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,10)

In [3]:
arr

array([9, 9, 1, 4, 3, 9, 5, 8, 3, 6])

In [4]:
# 保存数组到文件, 是二进制数据

np.save('D:/spider/numpyfile.npy', arr)

In [6]:
np.load('D:/spider/numpyfile.npy')

array([9, 9, 1, 4, 3, 9, 5, 8, 3, 6])

In [7]:
arr_2 = np.random.randint(1,10,10)

In [8]:
arr_2

array([6, 3, 4, 9, 6, 9, 5, 2, 1, 2])

In [9]:
# 将多个数组保存到文件, 将关键字传入

np.savez('D:/spider/numpyfile.npz', arr1=arr, arr2=arr_2)

In [10]:
all_arr = np.load('D:/spider/numpyfile.npz')

In [11]:
all_arr['arr1']

array([9, 9, 1, 4, 3, 9, 5, 8, 3, 6])