In [1]:
num_list = [i for i in range(10)]

In [2]:
import numpy as np

In [3]:
# array函数的使用
arr = np.array(num_list)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 通过array函数得到的是一个数组对象
type(arr)

numpy.ndarray

In [6]:
# 数组数据的类型
arr.dtype

dtype('int32')

In [7]:
# 数组的形状
arr.shape

(10,)

In [8]:
# 数组的维度
arr.ndim

1

In [13]:
# 全是0的数组
arr_zeros = np.zeros((3,6))

In [14]:
arr_zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
arr_one = np.ones((3,6))

In [16]:
arr_one

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [17]:
arr_one.dtype

dtype('float64')

In [18]:
arr_one.ndim

2

In [19]:
# 产生空数组,产生到的不一定是0,可能是垃圾值
np.empty((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
# 产生连续的整数数组
arange = np.arange(1,10)

In [32]:
arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# np.arange()函数产生的也是np.array类型的数据
type(arange)

numpy.ndarray

In [34]:
num_cut = arange[2:5]

In [35]:
num_cut

array([3, 4, 5])

In [36]:
num_cut[2] = 100

In [37]:
# np.arange()函数切片是在原视图切片,不是重新建立一个数组
arange

array([  1,   2,   3,   4, 100,   6,   7,   8,   9])

In [41]:
# 生成标准正态分布4*4数组
normal = np.random.normal(size=(4,4))

In [42]:
normal

array([[-0.46062954, -0.87948745, -1.30773434,  0.11712261],
       [ 1.5947786 , -1.80668149, -0.73317722,  1.28287675],
       [-1.32802755, -0.74481618, -1.24138278, -0.42025435],
       [-0.92776255,  0.51442433, -0.09663765, -1.30565437]])